export const ROUTES = {
	HOME: "/",
	FEATURES: "/features",
	PRICING: "/pricing",
	ROADMAP: "/roadmap",
	TERMS_OF_SERVICE: "/terms-of-service",
	PRIVACY_POLICY: "/privacy-policy",
	CONTACT: "/contact",
	SIGN_IN: "/sign-in",
	SIGN_UP: "/sign-up",
	FORGOT_PASSWORD: "/forgot-password",
	RESET_PASSWORD: "/reset-password",
	DASHBOARD: "/dashboard",
	CREATE: "/create",
	SETTINGS: "/settings",
	DECK: (deckId: string) => `/deck/${deckId}`,
} as const;
