export { default as FooterSection } from "../../layout/app-footer";
export { default as ContactSection } from "./contact-section";
export { default as CTASection } from "./cta-section";
export { default as HeroSection } from "./hero-section";
export { default as ProcessSection } from "./how-it-works-section";
export { default as ServicesSection } from "./services-section";
export { default as StatsSection } from "./stats-section";
export { default as TeamSection } from "./team-section";
export { default as TestimonialsSection } from "./testimonials-section";
