export { default as FooterSection } from "@/components/layout/app-footer";
export { default as ContactSection } from "@/components/sections/landing/contact-section";
export { default as CTASection } from "@/components/sections/landing/cta-section";
export { default as HeroSection } from "@/components/sections/landing/hero-section";
export { default as ProcessSection } from "@/components/sections/landing/how-it-works-section";
export { default as ServicesSection } from "@/components/sections/landing/services-section";
export { default as StatsSection } from "@/components/sections/landing/stats-section";
export { default as TeamSection } from "@/components/sections/landing/team-section";
export { default as TestimonialsSection } from "@/components/sections/landing/testimonials-section";
